/**
 * BULK CURRICULUM POPULATION - WEEKS 2-13 (Word-for-Word from Curriculum PDF)
 */

export const enhancedCurriculumWeeks = {
  w2: {
    id: 'w2',
    week: 'Week 02',
    title: 'Random Number Generation and Congruential Methods',
    shortDescription: 'Learn how to generate uniform pseudo-random numbers using congruential generators and apply them to fair coin tossing.',
    demoComponent: 'rnVisualization',
    learningOutcomes: [
      'Understand the congruential method algorithm for pseudo-random number generation',
      'Select proper constants a, c, and T to maximize the period of the generator',
      'Explain the concept of uniform random numbers on the [0,1) interval',
      'Simulate fair coin tossing using computer-generated random numbers',
      'Trace LCG operations step-by-step to compute subsequent random states'
    ],
    explanations: [
      {
        id: 'w2_exp_1',
        title: 'Random Number Generation (Pseudo R.N.)',
        type: 'concept',
        order: 1,
        content: 'There are many algorithms for random number generations, but we are going to emphasize the most common one, which is known as the Congruential method:\n\nR_{i+1} = (a * R_i + c) modulo T\n\nwhere:\n• R_{i+1} is the new uniform random number\n• R_i is the previous uniform random number\n• a, c, and T are arbitrary constants',
        sourceReference: 'Curriculum.pdf, Page 10'
      },
      {
        id: 'w2_exp_2',
        title: 'Tossing a Fair Coin Simulation',
        type: 'narrative',
        order: 2,
        content: 'The first example we are going to see is the simulation of tossing a fair coin. The first step is analyzing the problem. The fair coin means that when tossing that coin, the probability of head equals the probability of tail equals 50%. So, using a digital computer to simulate this phenomenon, we are going to use a uniform Random number generated by the package you are using, or you can write its code. Uniform random number means that you have a set of random numbers between 0 and 1, all with the same probability. But most languages generate uniform random number integers from a to b with equal probability.',
        sourceReference: 'Curriculum.pdf, Page 8'
      },
      {
        id: 'w2_exp_3',
        title: 'C++ Code for Coin Tossing Simulation',
        type: 'example',
        order: 3,
        content: 'See the following program written in C++:\n```cpp\n#include <iostream>\n#include <stdlib.h>\nvoid main(void)\n{\n    int x, number_of_trials, head = 0, tail = 0;\n    float phead, ptail, error_head, error_tail;\n    cout << "enter number of trials" << endl;\n    cin >> number_of_trials;\n    for (int i = 0; i < number_of_trials; i++)\n    {\n        x = random(2);\n        if (x == 1) head++;\n        else ++tail;\n    }\n    phead = head * 1.0 / number_of_trials;\n    ptail = tail * 1.0 / number_of_trials;\n    error_head = abs(((0.5 - phead) / 0.5) * 100);\n    error_tail = abs(((0.5 - ptail) / 0.5) * 100);\n    cout << "probability of head = " << phead << " with error =" << error_head << "%" << endl;\n    cout << "probability of tail = " << ptail << " with error =" << error_tail << "%" << endl;\n    cin >> x;\n}\n```',
        sourceReference: 'Curriculum.pdf, Page 8'
      }
    ],
    keyTerms: {
      'Congruential Method': 'Recurrence algorithm R_{i+1} = (a*R_i + c) mod T used to generate pseudorandom sequences.',
      'Modulo Arithmetic': 'Mathematical operation that finds the remainder when one integer is divided by another.',
      'Uniform Random Numbers': 'Numbers generated in a range [0,1) such that each subinterval has an equal probability of occurrence.',
      'Seed': 'The initial value R_0 used to start the congruential random number sequence.'
    },
    solvedProblems: [
      {
        id: 'w2_p1',
        title: 'Generate sequence from congruential generator',
        statement: 'For a = 1, c = 4, T = 5, R0 = 2 (seed); generate 10 random numbers.',
        method: 'Congruential modulo calculation',
        steps: [
          'R0 = 2',
          'R1 = Rem[{(1)(2) + 4}/5] = 1',
          'R2 = Rem[{(1)(1) + 4}/5] = 0',
          'R3 = Rem[{(1)(0) + 4}/5] = 4',
          'R4 = Rem[{(1)(4) + 4}/5] = 3',
          'R5 = Rem[{(1)(3) + 4}/5] = 2 (sequence repeats)'
        ],
        finalAnswer: 'Generated sequence: 2, 1, 0, 4, 3, 2, 1, 0, 4, 3'
      }
    ]
  },
  w3: {
    id: 'w3',
    week: 'Week 03',
    title: 'Daily Demand Simulation and Frequency Convergence',
    shortDescription: 'Simulate grocery demand based on relative frequencies and observe empirical probability convergence.',
    demoComponent: 'monteCarloConvergence',
    learningOutcomes: [
      'Formulate probability tables for discrete demand levels',
      'Establish cumulative range boundaries for mapping random numbers to demands',
      'Calculate theoretical expected daily demand mathematically',
      'Perform manual grocery demand simulation trials',
      'Quantify simulation error relative to the theoretical expected value'
    ],
    explanations: [
      {
        id: 'w3_exp_1',
        title: 'Daily Demand Simulation and Bowl Mapping',
        type: 'concept',
        order: 1,
        content: 'Get the average daily demand for a small grocery store selling fresh bread according to the following table:\nNote that the proportion of balls of a specific color corresponds exactly to the probability of a specific level of daily demand.\n\nTo simulate the daily demand (5 days):\nDraw one ball at a time, notice its color, and then place it back in the bowl. Then translate the outcomes into unique values of demand.',
        sourceReference: 'Curriculum.pdf, Page 9'
      },
      {
        id: 'w3_exp_2',
        title: 'Expected Daily Demand Formulas',
        type: 'example',
        order: 2,
        content: 'Expected value of simulated demand = 560 / 5 = 112 units/day\n\nAnalytical solution:\nExpected daily demand = 100(0.2) + 110(0.5) + 120(0.3) = 111 units/day',
        sourceReference: 'Curriculum.pdf, Page 9'
      }
    ],
    keyTerms: {
      'Expected Daily Demand': 'Weighted average of daily demand values multiplied by their respective probabilities.',
      'Bowl Mapping': 'A physical analogy where balls of different colors represent probability shares of discrete outcomes.',
      'Relative Frequency': 'The ratio of occurrences of a specific simulated outcome to the total number of trials.'
    },
    solvedProblems: [
      {
        id: 'w3_p1',
        title: '100-trial fair coin estimate',
        statement: 'Estimate P(Head) using 100 Monte Carlo draws.',
        method: 'Trial replication',
        steps: [
          'Generate 100 independent RN values.',
          'Count heads where RN<0.5.',
          'Divide head count by 100.'
        ],
        finalAnswer: 'Empirical estimate approaches 0.5 with enough trials.'
      }
    ]
  },
  w4: {
    id: 'w4',
    week: 'Week 04',
    title: 'Discrete Random Observations Mapping',
    shortDescription: 'Trace how single-digit random numbers are mapped to coin, die, and traffic light outcomes.',
    demoComponent: 'timeline',
    learningOutcomes: [
      'Map single-digit random numbers to fair coin tosses',
      'Handle reject boundaries when mapping digits to a six-faced die',
      'Construct mapping intervals matching non-equal probabilities (traffic light)',
      'Convert random digit streams into simulated observations'
    ],
    explanations: [
      {
        id: 'w4_exp_1',
        title: 'Generating Observations from Random Numbers',
        type: 'concept',
        order: 1,
        content: 'Use the one-digit Random Number (6, 3, 5, 0, 8) to generate random observations for:\n• Throwing an unbiased coin\n• Throwing a die\n• The color of a traffic light found by a randomly arriving car when it is green 40% of the time, yellow 10% of the time, and red 50% of the time',
        sourceReference: 'Curriculum.pdf, Page 9'
      },
      {
        id: 'w4_exp_2',
        title: 'Mapping Rules and Rejection Logic',
        type: 'example',
        order: 2,
        content: 'a) To simulate a coin using one digit R.N. (0-9), let 0–4 represent a Head and 5–9 represent a Tail; so the solution will be:\n   (6, 3, 5, 0, 8) → (T, H, T, H, T)\n\nb) To simulate a die using numbers 0–9. Let 1–6 represent the faces of the die; then 0, 7, 8, and 9 are rejected. So the solution will be:\n   (6, 3, 5, 0, 8) → (6, 3, 5, reject, reject)\n\nc) Divide 0–9 into 3 classes according to the given probability:\n• Green 40%: 0, 1, 2, 3\n• Yellow 10%: 4\n• Red 50%: 5, 6, 7, 8, 9\n   So (6, 3, 5, 0, 8) → (Red, Green, Red, Green, Red)',
        sourceReference: 'Curriculum.pdf, Page 9'
      }
    ],
    keyTerms: {
      'Rejection Mapping': 'A technique where random numbers falling outside the valid outcome range are discarded.',
      'Unbiased Experiment': 'An experiment where all outcomes are equally likely (e.g. fair coin or fair die).'
    },
    solvedProblems: [
      {
        id: 'w4_p1',
        title: 'Die simulation rejection check',
        statement: 'Trace the output for digits (7, 2, 9, 4, 0) when simulating a six-faced die.',
        method: 'Digit bounds mapping with rejects',
        steps: [
          'Digit 7 is outside 1-6 bounds => reject.',
          'Digit 2 is face 2.',
          'Digit 9 is outside 1-6 bounds => reject.',
          'Digit 4 is face 4.',
          'Digit 0 is outside 1-6 bounds => reject.'
        ],
        finalAnswer: 'Outcomes are (reject, 2, reject, 4, reject)'
      }
    ]
  },
  w5: {
    id: 'w5',
    week: 'Week 05',
    title: 'Probability and Distribution Theory & Insurance Case',
    shortDescription: 'Master discrete and continuous distributions, expected values, variances, and conditional branch decisions.',
    demoComponent: 'rnVisualization',
    learningOutcomes: [
      'Define set events, compound events, complements, and conditional probabilities',
      'Verify requirements for discrete probability functions and compute expected values and variances',
      'Evaluate continuous distributions using integration of probability density functions',
      'Assess functions of random variables and their moments',
      'Simulate multi-stage decision trees using two-stage random number streams (Insurance Problem)'
    ],
    explanations: [
      {
        id: 'w5_exp_1',
        title: 'Random Variables and Events',
        type: 'concept',
        order: 1,
        content: 'A random variable is a quantity whose value is determined by the outcome of a Random Experiment, i.e., the Random Variable X is a function whose domain is the event space and whose range is some subset of the real numbers:\nX: E → R\n\nAn event is some subset of the event space. The Complement of an event E is Ē, which contains the set of elements in Ω but not in E.\nNote that: E + Ē = Ω, E * Ē = Φ (null set).',
        sourceReference: 'Curriculum.pdf, Page 3'
      },
      {
        id: 'w5_exp_2',
        title: 'Discrete Probability Function and Moments',
        type: 'concept',
        order: 2,
        content: 'Every discrete probability function must satisfy:\n1. P(xi) ≥ 0 for all x.\n2. The cumulative distribution function (CDF) F(x) = P(X ≤ x).\n\nExpected value (Mean): E(X) = Σ xi P(xi)\nVariance: V(X) = Σ (xi - μ)² P(xi)\nStandard Deviation: S(X) = √V(X).',
        sourceReference: 'Curriculum.pdf, Page 4'
      },
      {
        id: 'w5_exp_3',
        title: 'Common Probability Distributions',
        type: 'concept',
        order: 3,
        content: '• Bernoulli: Discrete distribution with outcomes 0 (prob p) and 1 (prob q = 1 - p).\n• Uniform: Continuous distribution between a and b, f(x) = 1/(b - a) for a ≤ x ≤ b.\n• Poisson: Discrete count distribution, P(X = k) = (λ^k * e^(-λ)) / k!\n• Exponential: Continuous time distribution, f(x) = λ * e^(-λx) with F(x) = 1 - e^(-λx).\n• Normal: Continuous bell-curve, evaluated via standard normal Z = (X - μ)/σ.',
        sourceReference: 'Curriculum.pdf, Page 6'
      },
      {
        id: 'w5_exp_4',
        title: 'Sales of Life Insurance Problem',
        type: 'example',
        order: 4,
        content: 'Each time a house call is made:\n• 50% not interested in purchasing\n• 50% willing for further discussions\n\nAfter discussions:\n• 1/2 of the time the visit will result in "No Sale"\n• 1/3 of the time will result in a sale of a 10,000 L.E. policy\n• 1/6 of the time will result in a sale of a 20,000 L.E. policy\n\nUsing a simulated sample of 20 visits, determine the probability that a sale is made and the expected policy value.',
        sourceReference: 'Curriculum.pdf, Page 11'
      },
      {
        id: 'w5_exp_5',
        title: 'Insurance Theoretical vs Simulated Solution',
        type: 'example',
        order: 5,
        content: 'Theoretical Solution:\n• P(No Sale) = 0.75\n• P(Sale) = 0.25\n• P(10000 | sale) = 2/3 ≈ 0.667\n• P(20000 | sale) = 1/3 ≈ 0.333\n• Expected value = 0.667 * 10000 + 0.333 * 20000 = 13,333 L.E.\n\nSimulated Solution (20 visits sample):\n• 13 visits result in "No sale" => P(No sale) = 13/20 = 0.65\n• 7 visits result in sale (4 of 10k, 3 of 20k) => Expected Value = (4/7)*10000 + (3/7)*20000 = 14,286 L.E.',
        sourceReference: 'Curriculum.pdf, Page 11'
      }
    ],
    keyTerms: {
      'Random Variable': 'A function mapping the outcomes of a random experiment to real numbers.',
      'Conditional Probability': 'The probability of an event occurring given that another event has already occurred.',
      'Bernoulli Trial': 'An experiment with exactly two mutually exclusive outcomes: success and failure.'
    },
    solvedProblems: [
      {
        id: 'w5_p1',
        title: 'Expected value of policy sale',
        statement: 'Verify expected policy value given 10,000 L.E. sale probability is 2/3 and 20,000 L.E. is 1/3.',
        method: 'Expected value definition',
        steps: [
          'E(X) = Σ xi * P(xi)',
          'E(X) = 10000 * (2/3) + 20000 * (1/3)',
          'E(X) = 20000/3 + 20000/3 = 13,333.33 L.E.'
        ],
        finalAnswer: 'Expected value is 13,333.33 L.E.'
      }
    ]
  },
  w6: {
    id: 'w6',
    week: 'Week 06',
    title: 'Variance Reduction Techniques',
    shortDescription: 'Implement variance reduction via complementary random numbers and analyze convergence limits.',
    demoComponent: 'monteCarloConvergence',
    learningOutcomes: [
      'Apply sample size extension to reduce variance of simulated results',
      'Construct complementary random numbers to form antithetic variates',
      'Compare estimation errors between standard and complement trials',
      'Trace inverse transformations for probability density functions'
    ],
    explanations: [
      {
        id: 'w6_exp_1',
        title: 'Variance Reduction Concepts',
        type: 'concept',
        order: 1,
        content: 'Variance reduction increases the efficiency of simulations. One method is increasing sample size N. Since V(X_bar) is proportional to 1/N, larger samples reduce the variance of the estimator.\n\nExample: Use f(x) = e^(-x), an exponential distribution with mean λ = 1. Let Xi = -ln(1 - ri). Tracing 10 standard trials yields an estimated mean of 0.779 with 22.1% error.',
        sourceReference: 'Curriculum.pdf, Page 7'
      },
      {
        id: 'w6_exp_2',
        title: 'Complementary Random Numbers Method',
        type: 'example',
        order: 2,
        content: 'Instead of generating independent random numbers, use complement random numbers to form antithetic variates. For each ri generated, we also use (1 - ri).\n\nExample: Determine the mean of the random variable with CDF F(x) = x^2, 0 ≤ x ≤ 1. Set Xi = √ri.\n• Standard: 6 trials total 4.516, mean = 0.753 (13% error).\n• Complement: Combining ri and 1-ri yields a total of 4.143, mean = 0.691 (only 4% error against theoretical mean 2/3).',
        sourceReference: 'Curriculum.pdf, Page 7'
      }
    ],
    keyTerms: {
      'Antithetic Variates': 'A variance reduction technique that introduces negative correlation between variables using complements (1 - r).',
      'Estimation Error': 'The percentage difference between the simulated mean and the analytical expected value.'
    },
    solvedProblems: [
      {
        id: 'w6_p1',
        title: 'Compute error of complement simulation',
        statement: 'Given theoretical mean of 2/3 and simulated mean of 0.691, compute the percentage error.',
        method: 'Percentage error formula',
        steps: [
          'Error = |(Theoretical - Simulated) / Theoretical| * 100',
          'Error = |(2/3 - 0.691) / (2/3)| * 100',
          'Error = |(0.6667 - 0.691) / 0.6667| * 100 = 3.65%'
        ],
        finalAnswer: 'The simulation error is approximately 4%.'
      }
    ]
  },
  w7: {
    id: 'w7',
    week: 'Week 07',
    title: 'Introduction to Queueing Theory',
    shortDescription: 'Master queueing notation, performance metrics, and the analytical derivation of M/M/1 systems.',
    demoComponent: 'queueSystemTimeline',
    learningOutcomes: [
      'Describe queuing systems using A/B/C/D/E notation',
      'Identify key summary measures: queue length (Lq), time in system (W), and server utilization',
      'Derive queue state probabilities using stochastic balance equations',
      'Apply Little\'s formula to validate simulated delays against theoretical averages',
      'Calculate utilization boundaries for stable M/M/1 system queues'
    ],
    explanations: [
      {
        id: 'w7_exp_1',
        title: 'Queuing System Basics & Notation',
        type: 'concept',
        order: 1,
        content: 'A queuing system is a system in which customers arrive, wait if that service is not immediately available, receive the necessary service, and then depart.\n\nCharacteristics of any queuing system:\n(A) The arrival pattern (distribution of arriving customers)\n(B) The service process (distribution of service time)\n(C) The number of parallel servers\n(D) The system capacity\n(E) The queuing discipline (FIFO, LIFO, priority)\n\nSo any queuing system can be described as A/B/C/D/E.',
        sourceReference: 'Curriculum.pdf, Page 7'
      },
      {
        id: 'w7_exp_2',
        title: 'Items of Interest (Summary Measures)',
        type: 'concept',
        order: 2,
        content: 'The primary metrics of interest concerning any queuing model are:\n1. Queuing length (Lq)\n2. Time in the system (W)\n3. Idle and busy time of a server',
        sourceReference: 'Curriculum.pdf, Page 8'
      },
      {
        id: 'w7_exp_3',
        title: 'M/M/1/∞/FIFO Balance Equations',
        type: 'concept',
        order: 3,
        content: 'Using stochastic balance equations:\n• At point S₀: μ * p₁ = λ * p₀ ⇒ p₁ = (λ/μ) * p₀\n• At point S₁: (λ + μ) * p₁ = λ * p₀ + μ * p₂ ⇒ p₂ = (λ/μ)² * p₀\n• In general, p_n = (λ/μ)^n * p₀\n\nExpected number in the system (L): L = Σ n * p_n\nExpected number in the queue (Lq): Lq = Σ (n - 1) * p_n\n\nUsing Little’s formula:\n• Expected time in the system: W = L / λ\n• Expected time in the Queue: Wq = Lq / λ',
        sourceReference: 'Curriculum.pdf, Page 8'
      }
    ],
    keyTerms: {
      'Queuing Discipline': 'The rule determining the order in which customers are served (e.g., First-In, First-Out).',
      'Little’s Formula': 'The algebraic relation W = L / λ connecting average count, arrival rate, and stay time.',
      'Stochastic Balance': 'The steady-state condition where the rate of transitions into a state equals the rate of transitions out of it.'
    },
    solvedProblems: [
      {
        id: 'w7_p1',
        title: 'Derive p_2 probability in terms of p_0',
        statement: 'Given arrival rate λ and service rate μ, prove that p2 = (λ/μ)^2 * p0.',
        method: 'State transition balancing',
        steps: [
          'State 1 balance: (λ + μ)p1 = λp0 + μp2',
          'Substitute p1 = (λ/μ)p0 into the equation:',
          '(λ + μ)(λ/μ)p0 = λp0 + μp2 => (λ^2/μ + λ)p0 = λp0 + μp2',
          'Subtract λp0 from both sides: (λ^2/μ)p0 = μp2',
          'Divide by μ: p2 = (λ/μ)^2 * p0'
        ],
        finalAnswer: 'p2 = (λ/μ)^2 * p0'
      }
    ]
  },
  w8: {
    id: 'w8',
    week: 'Week 08',
    title: 'Random Observations and Inverse Transform',
    shortDescription: 'Generate random observations for Uniform and Exponential distributions using the inverse CDF transform.',
    demoComponent: 'rnVisualization',
    learningOutcomes: [
      'Differentiate between simple discrete mapping and continuous inverse methods',
      'Derive the inverse transform formula for continuous Uniform distributions',
      'Derive the inverse transform formula for continuous Exponential distributions',
      'Convert random decimals into exact simulated service/arrival intervals'
    ],
    explanations: [
      {
        id: 'w8_exp_1',
        title: 'Allocation vs Inverse Method',
        type: 'concept',
        order: 1,
        content: '1. For a Simple Discrete Distribution, we use the allocation method (mapping cumulative ranges as seen in the grocery demand problem).\n\n2. For Continuous Distribution, we use the inverse method if and only if the distribution is reversible.',
        sourceReference: 'Curriculum.pdf, Page 10'
      },
      {
        id: 'w8_exp_2',
        title: 'Uniform and Exponential Inverse Transforms',
        type: 'example',
        order: 2,
        content: '• Uniform Distribution U(a, b): F(x) = (x - a)/(b - a) = r ⇒ X = a + r(b - a)\n\n• Exponential Distribution: F(x) = 1 - e^(-λx) = r ⇒ e^(-λx) = 1 - r ⇒ X = -(1/λ) * ln(1 - r)',
        sourceReference: 'Curriculum.pdf, Page 10'
      }
    ],
    keyTerms: {
      'Inverse CDF': 'The inverse function of the cumulative distribution function, used to map uniform variables to target distributions.',
      'Reversibility': 'The mathematical property allowing a function to be inverted analytically to solve for the target variable.'
    },
    solvedProblems: [
      {
        id: 'w8_p1',
        title: 'Generate exponential observation',
        statement: 'Generate an exponential observation with mean rate λ = 2 for random number r = 0.4.',
        method: 'Exponential inverse transform',
        steps: [
          'Formula: X = - (1/λ) * ln(1 - r)',
          'Substitute values: X = - (1/2) * ln(1 - 0.4)',
          'X = - 0.5 * ln(0.6) = - 0.5 * (-0.5108) = 0.2554'
        ],
        finalAnswer: 'Simulated observation is 0.2554 time units.'
      }
    ]
  },
  w9: {
    id: 'w9',
    week: 'Week 09',
    title: '7th Exam Debrief and Integrated Trace Review',
    shortDescription: 'Work through 7th exam answer sets to consolidate random mapping, queue traces, and performance metrics.',
    demoComponent: 'inventoryPolicyVisualizer',
    learningOutcomes: [
      'Review 7th week exam questions and analyze common errors in manual traces',
      'Quantify stockouts, carrying levels, and service metrics under different inventory policies',
      'Compare inventory replenishment strategies (reorder point vs periodic review)',
      'Analyze queue length distributions and server utilization from exam trace tables',
      'Verify simulation correctness using conservation equations and sanity checks'
    ],
    explanations: [
      {
        id: 'w9_exp_1',
        title: 'Review of 7th Exam Performance',
        type: 'narrative',
        order: 1,
        content: 'The 7th exam tests core mechanics: random mapping, manual queue traces, and basic inventory logic. Common errors include: off-by-one errors in scheduling departures, incorrect cumulative probability range mapping (e.g. mapping RN=40 to the wrong interval), and confusing clock time with activity duration. Debriefing these errors is essential before moving to multi-stage and finite-source models.',
        sourceReference: '7th exam answer.pdf, Question 1 Analysis'
      },
      {
        id: 'w9_exp_2',
        title: 'Inventory Replenishment and Reorder Points',
        type: 'concept',
        order: 2,
        content: 'In inventory simulation, we track daily demand and stock levels. A reorder point (RP) policy triggers a replenishment order of size Q when inventory drops to or below RP. The order arrives after a lead time L. Tracing this requires maintaining the state: ending inventory, outstanding orders, and arrival schedules.',
        sourceReference: 'Curriculum.pdf, Inventory Policy'
      },
      {
        id: 'w9_exp_3',
        title: 'Confusing Lead Time with Arrival',
        type: 'warning',
        order: 3,
        content: 'WARNING: When an order is placed on day t with lead time L, it arrives at the START of day t+L (or end of day t+L-1 depending on convention). Be consistent with your time index. Do not double-order while an order is already in transit unless the policy explicitly allows multiple outstanding orders.',
        sourceReference: 'Curriculum.pdf, Inventory Warnings'
      },
      {
        id: 'w9_exp_4',
        title: 'Trace Table for Reorder Point (RP=5, Q=10)',
        type: 'example',
        order: 4,
        content: 'Initial stock = 8. Day 1: demand = 4, ending stock = 4 <= RP. Trigger order of 10. Lead time = 2 days. Order arrives at start of Day 3. Day 2: demand = 2, ending stock = 2. Day 3: order of 10 arrives, stock = 2+10 = 12. Demand = 3, ending stock = 9.',
        sourceReference: 'Session2_BusinessLogic.md, Section 4'
      }
    ],
    keyTerms: {
      'Reorder Point (RP)': 'The threshold inventory level that triggers a replenishment order.',
      'Order Quantity (Q)': 'The fixed batch size ordered when inventory hits the reorder point.',
      'Lead Time': 'The delay (in days or hours) between placing an order and receiving the stock.',
      'Stockout': 'A situation where demand exceeds available stock, resulting in lost sales or backorders.',
      'Carrying Cost': 'The cost of holding inventory in stock over a period of time.'
    },
    solvedProblems: [
      {
        id: 'w9_p1',
        title: 'Policy comparison under same demand stream',
        statement: 'Compare inventory policies RP=5 and RP=8 under identical daily demands.',
        method: 'Controlled experiment simulation',
        steps: [
          'Run both policies with same random demand sequence.',
          'Track stockouts and average inventory for each policy.',
          'Compare service level versus holding burden.'
        ],
        finalAnswer: 'Higher reorder point usually lowers stockouts and raises average stock.'
      },
      {
        id: 'w9_p2',
        title: 'Stockout-day counting',
        statement: 'Given ending stocks [3,1,0,-1,4,0], count stockout days and stockout ratio.',
        method: 'Threshold-based KPI',
        steps: [
          'Mark day as stockout when ending stock <= 0.',
          'Count marked days in horizon.',
          'Divide by total days to obtain ratio.'
        ],
        finalAnswer: 'Stockout occurred on 3 of 6 days (50%).'
      },
      {
        id: 'w9_p3',
        title: 'Average inventory level from trace',
        statement: 'Daily ending stocks are [10,8,7,5,9]. Compute average inventory.',
        method: 'Time-average estimate',
        steps: [
          'Sum levels: 10+8+7+5+9=39.',
          'Divide by 5 days.',
          'Interpret result as average carrying level.'
        ],
        finalAnswer: 'Average inventory is 7.8 units.'
      }
    ]
  },
  w10: {
    id: 'w10',
    week: 'Week 10',
    title: 'Machine Maintenance and Replacement Simulation',
    shortDescription: 'Model equipment failure/repair and evaluate maintenance and replacement timing through simulated traces.',
    demoComponent: 'queueSystemTimeline',
    learningOutcomes: [
      'Model failure times and repair times as stochastic processes',
      'Simulate machine downtime and calculate system availability',
      'Compare preventive maintenance (scheduled replacement) vs breakdown maintenance (replace on failure)',
      'Trace queue dynamics at a repair shop with limited repairmen',
      'Perform cost-benefit analysis for maintenance policies'
    ],
    explanations: [
      {
        id: 'w10_exp_1',
        title: 'Equipment Reliability and Simulation',
        type: 'narrative',
        order: 1,
        content: 'Manufacturing systems rely on machines that break down. Reliability simulation models the time-to-failure (TTF) and time-to-repair (TTR) using exponential or Weibull distributions. By simulating these run-fail-repair cycles, engineers estimate long-term availability and optimize maintenance staffing.',
        sourceReference: 'Week 10.pdf, Section 1'
      },
      {
        id: 'w10_exp_2',
        title: 'Preventive vs Run-to-Failure Maintenance',
        type: 'concept',
        order: 2,
        content: 'Preventive maintenance (PM) replaces parts at scheduled intervals before they fail. Breakdown maintenance (BM) replaces parts only after failure. PM reduces downtime but increases part replacement costs. BM utilizes the full life of the part but incurs high unscheduled downtime costs. Simulation evaluates the optimal PM interval.',
        sourceReference: 'Week 10.pdf, PM vs BM'
      },
      {
        id: 'w10_exp_3',
        title: 'Simulating Tube Replacement',
        type: 'example',
        order: 3,
        content: 'A machine has three vacuum tubes. When one fails, the machine stops. We compare: (1) Replace only the failed tube (cost $20, takes 1 hour). (2) Replace all three tubes when one fails (total cost $50, takes 2 hours). By running a 1000-hour simulation, we find which policy minimizes total cost (replacement cost + downtime loss).',
        sourceReference: 'week 10 full solution.pdf, Tube Problem'
      }
    ],
    keyTerms: {
      'Time-To-Failure (TTF)': 'The duration a machine operates continuously before breaking down.',
      'Time-To-Repair (TTR)': 'The duration required to restore a failed machine to operating state.',
      'Availability': 'The fraction of time the machine is in operating condition (Uptime / Total Time).',
      'Preventive Maintenance': 'Scheduled upkeep performed to prevent failures before they occur.',
      'Breakdown Maintenance': 'Reactive repair performed only after a failure has occurred.'
    },
    solvedProblems: [
      {
        id: 'w10_p1',
        title: 'Server utilization from busy time',
        statement: 'Busy time is 45 minutes over a 60-minute run. Compute utilization.',
        method: 'Direct ratio',
        steps: [
          'Use rho = busy time / total time.',
          'Substitute 45/60.',
          'Convert to percentage.'
        ],
        finalAnswer: 'Utilization is 0.75 (75%).'
      },
      {
        id: 'w10_p2',
        title: 'Idle time and percentage',
        statement: 'If total run is 8 hours and busy time is 5.5 hours, compute idle time and idle percent.',
        method: 'Complementary performance metrics',
        steps: [
          'Idle time = total - busy = 2.5 hours.',
          'Idle fraction = 2.5/8.',
          'Convert to percentage.'
        ],
        finalAnswer: 'Idle time is 2.5 hours, i.e., 31.25%.'
      },
      {
        id: 'w10_p3',
        title: 'Failure-repair queue interpretation',
        statement: 'In the week-10 full-solution context (frequent tube failures), explain effect of higher failure rate on queue metrics.',
        method: 'Queue pressure reasoning',
        steps: [
          'More failures increase arrival rate to repair queue.',
          'If service capacity unchanged, waiting and queue length rise.',
          'Higher waiting raises downtime and may lower effective throughput.'
        ],
        finalAnswer: 'Higher failure intensity worsens waiting, queue length, and downtime unless repair capacity is improved.'
      }
    ]
  },
  w11: {
    id: 'w11',
    week: 'Week 11',
    title: 'Two-Stage Assembly Line (Bob and Ray)',
    shortDescription: 'Simulate tandem service stations, identify waiting buildup, and quantify bottleneck effects.',
    demoComponent: 'assemblyLineBottleneck',
    learningOutcomes: [
      'Model multi-stage serial production lines with inter-stage storage (buffers)',
      'Identify bottleneck stations by comparing service rates and utilizations',
      'Trace blocking (upstream idle) and starving (downstream idle) in assembly lines',
      'Evaluate the impact of buffer capacity on line throughput',
      'Optimize work-in-progress (WIP) levels across stages'
    ],
    explanations: [
      {
        id: 'w11_exp_1',
        title: 'Tandem Queues and Serial Assembly',
        type: 'narrative',
        order: 1,
        content: 'In a serial line, items move through stations in sequence. The output of Station 1 becomes the input to Station 2. If Station 2 is slower than Station 1, a queue builds up between them. If the inter-stage buffer is full, Station 1 is blocked (cannot release its completed item and must stop). If the buffer is empty, Station 2 is starved (idle waiting for input).',
        sourceReference: 'Week 11.pdf, Section 2'
      },
      {
        id: 'w11_exp_2',
        title: 'Bob and Ray Line Bottleneck',
        type: 'concept',
        order: 2,
        content: 'Bob (Stage 1) takes 3 min/item; Ray (Stage 2) takes 5 min/item. Ray is the bottleneck because his service rate (12 items/hr) is lower than Bob\'s (20 items/hr). Long-run line throughput is limited to 12 items/hr. Bob will be forced to be idle (blocked) 40% of the time, and a queue will build up in front of Ray.',
        sourceReference: 'Assembly Lines-(Bob and Ray) full solution.pdf'
      },
      {
        id: 'w11_exp_3',
        title: 'Blocking and Starvation',
        type: 'warning',
        order: 3,
        content: 'WARNING: In manual traces, blocking occurs when a station finishes work but the next station\'s queue/buffer is full. The finished item remains at the current station, keeping it busy/blocked. Starvation occurs when a station is idle because no items are available in its queue.',
        sourceReference: 'Week 11.pdf, Operational Constraints'
      }
    ],
    keyTerms: {
      'Tandem Queue': 'A sequence of service facilities where customers must go from one queue/server to the next.',
      'Bottleneck': 'The stage in a production process that has the lowest capacity and limits overall throughput.',
      'Blocking': 'The state where an upstream server completes service but cannot release the item because the downstream buffer is full.',
      'Starving': 'The state where a downstream server is idle because no items are ready from the upstream server.',
      'Work-in-Progress (WIP)': 'The total number of items currently in the production line (in queues or at servers).'
    },
    solvedProblems: [
      {
        id: 'w11_p1',
        title: 'Bob-Ray bottleneck identification',
        statement: 'In two-stage line, Bob=3 min/item and Ray=5 min/item. Identify bottleneck.',
        method: 'Service-rate comparison',
        steps: [
          'Convert times to rates: Bob 20 items/hr, Ray 12 items/hr.',
          'Lower processing rate determines bottleneck.',
          'Infer queue buildup before slower stage.'
        ],
        finalAnswer: 'Ray (stage 2) is bottleneck.'
      },
      {
        id: 'w11_p2',
        title: 'Line utilization by stage',
        statement: 'Total run is 120 min. Bob busy 90 min, Ray busy 110 min. Compute stage utilizations.',
        method: 'Per-station utilization metric',
        steps: [
          'Bob utilization = 90/120.',
          'Ray utilization = 110/120.',
          'Compare values to explain where congestion forms.'
        ],
        finalAnswer: 'Bob utilization is 75%; Ray utilization is about 91.7%, confirming Ray as tighter stage.'
      },
      {
        id: 'w11_p3',
        title: 'Throughput estimate for serial stations',
        statement: 'Given deterministic stage times 4 min then 6 min/item, estimate long-run throughput.',
        method: 'Bottleneck-capacity throughput',
        steps: [
          'Compute capacities: stage1=15/hr, stage2=10/hr.',
          'Serial line throughput limited by minimum capacity.',
          'Use slower stage as long-run output rate.'
        ],
        finalAnswer: 'Throughput is limited to about 10 items/hour.'
      }
    ]
  },
  w12: {
    id: 'w12',
    week: 'Week 12',
    title: 'Time-Advance Clock Mechanics',
    shortDescription: 'Trace how events are processed under Periodic Scan (Fixed-Increment) vs Event Scan (Next-Event) clock mechanics.',
    demoComponent: 'repairmanQueueComparison',
    learningOutcomes: [
      'Contrast simulation time vs run time',
      'Explain Periodic Scan mechanics and cumulative interval updates',
      'Explain Event Scan mechanics and Future Event List priority scheduling',
      'Solve a 10-minute service station timeline trace comparison'
    ],
    explanations: [
      {
        id: 'w12_exp_1',
        title: 'Simulation Time vs Run Time',
        type: 'concept',
        order: 1,
        content: 'There are two time references used in simulation:\n1. Simulation Time: The period of time simulated by the model – 30 min., 5 years, 100 years, whatever interval the researcher is interested in. This time is reset to zero at the beginning of the simulation run and acts as a counter to the number of simulation time units.\n2. Run Time: The time that the computer takes to simulate the period of interest.',
        sourceReference: 'Curriculum.pdf, Page 11'
      },
      {
        id: 'w12_exp_2',
        title: 'The Periodic Scan Technique',
        type: 'concept',
        order: 2,
        content: 'In this technique, the simulation clock is adjusted by one predetermined uniform unit and then examines the system to determine whether any events occurred during that interval. If any occurred, the event or events are simulated; otherwise, no action is taken. The simulation clock is then advanced another unit, and the process is repeated. In this technique, the exact time of the occurrence of a particular event is largely ignored. All events that occur during a given interval are treated as if these events occurred at the end of that interval.',
        sourceReference: 'Curriculum.pdf, Page 11'
      },
      {
        id: 'w12_exp_3',
        title: 'The Event Scan Technique',
        type: 'concept',
        order: 3,
        content: 'In this technique, the clock is advanced by the amount necessary to trigger the occurrence of the next event. Thus, the time advance intervals are of variable lengths. While some information can be lost in the periodic scan, the event scan avoids this problem because the clock is advanced only to the next occurrence time. In periodic scan, the exact occurrence time of events is not known because each event is treated as if it occurred at the end of the time interval in which it occurred. This problem is overcome in the Event Scan approach.',
        sourceReference: 'Curriculum.pdf, Page 12'
      },
      {
        id: 'w12_exp_4',
        title: '10-Minute Station Trace Comparison',
        type: 'example',
        order: 4,
        content: 'Consider a single-bay service station for a period of ten minutes. Assume the system is empty at start and end. Four customers are serviced; arrivals occur at times 1.8, 3.2, 6.1, and 7.4, and service completions occur at times 2.6, 4.8, 7.3, and 8.1.\n\n• Periodic Scan (dt=1 min): Arrival events are treated as occurring at interval boundaries. C3 and A4 are treated as occurring simultaneously at clock 8.0, even though C3 actually occurred before A4.\n• Event Scan: Clock jumps to 1.8, 2.6, 3.2, 4.8, 6.1, 7.3, 7.4, 8.1 exactly, preserving event order and system state accurately.',
        sourceReference: 'Curriculum.pdf, Page 12'
      }
    ],
    keyTerms: {
      'Simulation Clock': 'A variable in a simulation model that represents the current value of simulated time.',
      'Periodic Scan': 'Clock advance by a constant time increment, checking for events at each step.',
      'Event Scan': 'Clock advance to the next scheduled event time from the FEL.'
    },
    solvedProblems: [
      {
        id: 'w12_p1',
        title: 'Periodic scan event simultaneity',
        statement: 'Given event times A@1.8, C@2.6, with dt=1, show how periodic scan groups them.',
        method: 'Periodic scan mapping',
        steps: [
          'Clock at 0.0 -> no events.',
          'Clock at 1.0 -> no events.',
          'Clock at 2.0 -> process arrival A (which occurred at 1.8).',
          'Clock at 3.0 -> process completion C (which occurred at 2.6).'
        ],
        finalAnswer: 'Arrival is processed at t=2.0; completion is processed at t=3.0.'
      }
    ]
  },
  w13: {
    id: 'w13',
    week: 'Week 13',
    title: 'Continuous M/M/1 Clock Mechanics & Finite-Source Repairman',
    shortDescription: 'Simulate continuous M/M/1 systems under both time-driven and event-driven advancements, and trace closed repairman loops.',
    demoComponent: 'eventVsPeriodicComparison',
    learningOutcomes: [
      'Compare time scan vs event scan calculations for continuous distributions',
      'Determine arrival/departure event probabilities in a fixed time increment',
      'Calculate average machine downtime for finite machine-breakdown models',
      'Select proper clock advance strategy for steady-state queue validations'
    ],
    explanations: [
      {
        id: 'w13_exp_1',
        title: 'Time Scan vs Event Scan for Continuous M/M/1',
        type: 'concept',
        order: 1,
        content: 'Simulate a system M/M/1 with arrival rate λ = 20/h and service rate μ = 25/h. Assuming the system is empty at time zero.\n\n1. Using Time Scan (dt = 1 minute):\n• P(arrival in one minute period) = 1 – e^(-λt) = 1 – e^(-1/3 * 1) ≈ 0.281\n• P(departure in one minute period) = 1 – e^(-μt) = 1 – e^(-5/12 * 1) ≈ 0.341\nLet ranges be:\n• 0 ≤ R.N. ≤ 0.281 → Arrival\n• 0 ≤ R.N. ≤ 0.341 → Departure\n\n2. Using Event Scan:\n• Time until next arrival: t_arr = - (1/λ) * ln(1 - R)\n• Time until next departure: t_dep = - (1/μ) * ln(1 - R)',
        sourceReference: 'Curriculum.pdf, Page 12'
      },
      {
        id: 'w13_exp_2',
        title: 'Machine Breakdown and Repairperson Example',
        type: 'example',
        order: 2,
        content: 'A bank of machines in a manufacturing shop breaks down according to a given interarrival time distribution. The time it takes one repair person to complete the repair of a machine is given in the service time distribution.\n\nSimulate the breakdown of 5 machines. Calculate the average machine downtime using two repair persons. Both repair persons cannot work on the same machine.\n\nR.N. sequence: 30, 81, 02, 91, 51, 08, 28, 44, 86, 84, 29, 08, 37, 34, 99.',
        sourceReference: 'Curriculum.pdf, Page 12'
      },
      {
        id: 'w13_exp_3',
        title: 'Two-Stage Assembly Line Model',
        type: 'example',
        order: 3,
        content: 'Two-stage assembly lines are producing a large product. There is no room in between the two lines; so the output of the first line is fed to the second line directly, else the first line must wait until the second line is free. The service distributions for both lines are given. For 10 products:\n• Total service time for 1st line = 470 seconds\n• Total service time for 2nd line = 430 seconds\n• Output rate average = 600 / 10 = 60 seconds\n• Utilization of 1st line = 470 / 530 ≈ 88.7%\n• Utilization of 2nd line = 430 / 550 ≈ 78.2%',
        sourceReference: 'Curriculum.pdf, Page 13'
      }
    ],
    keyTerms: {
      'Transition Probability': 'The probability of an arrival or departure occurring within a fixed time step delta-t.',
      'Downtime': 'The total duration a machine spends in a failed or queueing state before repair completes.',
      'Tandem Line Blocking': 'When a serial stage must stop operating because the downstream buffer is full and cannot receive parts.'
    },
    solvedProblems: [
      {
        id: 'w13_p1',
        title: 'M/M/1 transition probability',
        statement: 'For λ = 20/h, compute probability of arrival in a 1-minute period.',
        method: 'Poisson arrival probability',
        steps: [
          't = 1 minute = 1/60 hours.',
          'P(Arrival) = 1 - e^(-λt) = 1 - e^(-20 * (1/60)) = 1 - e^(-1/3)',
          'P(Arrival) = 1 - e^(-0.3333) = 1 - 0.7165 = 0.2835'
        ],
        finalAnswer: 'Arrival probability is 0.281 (approx 28.1%).'
      }
    ]
  }
};

export default enhancedCurriculumWeeks;
